### ISSUE TITLE
Rename repo to kyma-cli

### ISSUE THREAD

**Issue by sjanota** [kyma-incubator/kyma-cli#12]
Current project name `kymactl` suggests binary name (like `kubectl`). However, the binary is named differently: `kyma`. I suggest changing name of the project to `kyma-cli` or simply `cli`.

**Comment by a-thaler** [comment]
Let's rename it to kyma-ctl. First I will see that the two existing PRs are getting merged to reduce efforts.

**Comment by a-thaler** [comment]
I renamed the repo and adjusted the content.
Renamed test-infra configuration as well
