### ISSUE TITLE
Support custom admin password for installation

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/kyma-cli#36]
The default Kyma installation will configure dex with an initial generated admin password.
Instead of figuring out the password after installation and potentially changing it, there should be a way to configure the password as part of installation.

Proposal:
Introduce `-p/--password` flag to `install` command which configured the password for the installer.
Assure that the password gets printed nowhere, especially not at the summary section at the end of installation.

**Comment by igor-karpukhin** [comment]
https://github.com/kyma-incubator/kyma-cli/pull/55 - solves this. Use the `-p` option to provide the custom password for the installation.
