### ISSUE TITLE
Support for knative flag on kyma installation

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/kyma-cli#38]
The current installation scripts have a special flag to indicate a kyma installation based on knative. That mode will preset the minikube memory and disk settings and will preset the installer configuration.

Goal: Support installation of kyma in knative mode

**Comment by sjanota** [comment]
As far as I know Kyma will be installed with Knative by default in 0.9, so I think we need to wait a moment to see the outcome. @a-thaler you can sync with @abbi-gaurav on this one.

**Comment by a-thaler** [comment]
Indeed with kyma 1.0 knative will be a mandatory dependency, so not worth of investing here anymore
