### ISSUE TITLE
Support of configuration overrides

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/kyma-cli#40]
# Background
To install kyma you need to apply the installer CR as well as a set of predefined configMaps which you can customize. At the moment you can specify a custom yaml file containing the configMaps and the installer CR all in one file using the --config flag at install

# Motivation
Sometimes it is handy to replace just the installer CR or just one dedicated configMap. The rest of the configuration should be still based on the base yaml file provided by the release. To easily manage your changes it will be helpful to configure the different customizations individually, not all in one file.

# Goal
Instead of replacing the full yaml config using the --config flag, support a override of the configmaps and the installer cr defined in the base yaml file
Before: `kyma install --config customConfig.yaml`
After: `kyma install --config monitoringConfig.yaml --config installerCR.yaml --config eventBusConfig.yaml`

**Comment by igor-karpukhin** [comment]
https://github.com/kyma-incubator/kyma-cli/pull/52 - solves this. `-o` option allows providing multiple configuration files, each file may contain more than one config map, secret, etc.
