### ISSUE TITLE
Support for kyma 0.8

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/kyma-cli#42]
Kyma 0.8 will be released in a moment and the CLI should support it.

- Update default kyma release so that the new config and installer files will be applied
- Update supported kubectl and minikube version
- it might be required to fix first: https://github.com/kyma-incubator/kyma-cli/issues/31
- Verify that minikube provisioning, install/uninstall works

**Comment by sjanota** [comment]
This one also is critical: #37. Without it console tests will always fail.

**Comment by a-thaler** [comment]
done
