### ISSUE TITLE
Continue with the installation even if I choose No for deleteing previous minikube

### ISSUE THREAD

**Issue by obadrawi** [kyma-incubator/kyma-cli#47]
So there is a problem with minikube in windows. Although I actually deleted minikube and could provision a new minikube cluster the status of minikube shows that it's still installed and when I use the CLI to provision a new cluster it asks me if I want to delete the previous cluster. If I choose Yes it fails and if I choose No it exits so then I am stuck and can't use the tool. So I would Like to suggest that if I choose No the provisioning continues without the delete command

**Comment by sjanota** [comment]
1. @obadrawi Did you literally type `Yes` and `No`? The scripts reacts only to `y` and `n`, but we definitely could be more liberal here.

2. @a-thaler Actually behaviour described by @obadrawi is what Kyma does right now. It was introduced some time ago in PR kyma-project/kyma#2156. To be consistent we should fix it.

**Comment by obadrawi** [comment]
@sjanota  Yes I type only **y** and **n**

**Comment by a-thaler** [comment]
yep, let's not exit but print a message that deletion is skipped

**Comment by a-thaler** [comment]
fixed as discussed
