### ISSUE TITLE
Newer minikube version fails

### ISSUE THREAD

**Issue by a-thaler** [kyma-incubator/kyma-cli#59]
Starting from minikube version 0.34.1 the "kyma provision minikube" command seems to fail like that:

```
✕ Adjusting minikube cluster
Error: Failed executing command ’minikube ssh -- ‘sudo sysctl -w fs.inotify.max_user_instances=524288’' with output ’bash: sudo sysctl -w fs.inotify.max_user_instances=524288: command not found
```
Executing the command manually is working without error message.

**Comment by igor-karpukhin** [comment]
https://github.com/kyma-incubator/kyma-cli/pull/60

**Comment by a-thaler** [comment]
There was a quoting problem which got fixed
